### ISSUE TITLE
文件名没有encode的问题

### ISSUE THREAD

**Issue by wastee** [zaibuyidao/YS_ReaScripts#1]
在当归蛋的xml源里，这一行里的文件名没有被正确encode。

https://github.com/zaibuyidao/YS_ReaScripts/blob/main/index.xml#L983

访问会出现404

![图片](https://github.com/user-attachments/assets/c7f23c70-27f8-479c-bdf5-5fe72055b447)

正确是 https://github.com/zaibuyidao/YS_ReaScripts/raw/4c0897c813917a4384976ea63c434902bfe0edb2/MIDI%20Editor/YS_%E9%9F%B3%E7%AC%A6%E7%A2%8E%E6%8B%A8(mandolin%EF%BC%8Cguitar..).lua

即最后的文件名不一样（逗号这些）。

不清楚是否 reapack 自动生成的问题，也不清楚现在 reapack 是否已经包含这些符号的 url encode。

**Comment by zaibuyidao** [comment]
谢谢反馈，确实是文件名中的逗号导致了问题，我已经进行了修正。请您再确认一下，是否一切正常？

**Comment by wastee** [comment]
谢谢，正常了。
